### PR TITLE
Add the `festivalId` field to the Activity type

### LINKED ISSUE #39: Expose the festival ID in the activities API
Could the `pac_festival_id` field be included in the `activities.json` API response please? Fine for it to be gated on access.

We currently expose the `year` field, however, in practice that is a mess. For 2023 the values `2023`, `20236`, `202306` and `202309` were used (for unknown reason).

I see that other users, e.g. the [event viewer](https://github.com/AnimeNL/event-viewer/blob/master/src/libs/anime.js#L93), rely on the `timeslots.json` API with a date filter instead, most likely to work around this issue. I'd like to avoid that because that API follows a very different structure, and is rather wasteful in its response.

Happy to send a (naive) PR if that helps, but I have no idea how to test it, and can't deploy it.

### PR DESCRIPTION
**Pull request by beverloo**
Fixes #39

### CODE REVIEW

**Comment by beverloo** [comment]
Field definition is as follows:
```sql
CREATE TABLE if not exists plan__activities (
    pac_festival_id         bigint unsigned not null references booth__festival_settings (bfs_id)
)
```

I just re-read your message on #39 - I don't think it's a bug in the REST API that many different values are used for the year, but rather that the inconsistent values exist in the database. The festival filter in AnPlan uses the `pac_festival_id` as well.

**Comment by janvernieuwe** [comment]
@beverloo we are go!
wel ff main in je branch mergen!

**Comment by beverloo** [comment]
Done, PTAL!

**Comment by janvernieuwe** [comment]
> Field definition is as follows:
> 
> ```sql
> CREATE TABLE if not exists plan__activities (
>     pac_festival_id         bigint unsigned not null references booth__festival_settings (bfs_id)
> )
> ```
> 
> I just re-read your message on #39 - I don't think it's a bug in the REST API that many different values are used for the year, but rather that the inconsistent values exist in the database. The festival filter in AnPlan uses the `pac_festival_id` as well.

@mddejong this is already this way in anplan? or not?
If so i will merge :rocket:

**Comment by beverloo** [comment]
For the record, `pac_festival_id` is:

- What [AnPlan](https://anplan.animecon.nl/timeslots) uses to filter by event presently, and,
- Included in [this .sql](https://github.com/mddejong/TicketBooth/blob/3354e2fb329fbeb1cabe8135d2ec4f9a6a4c522e/application/config/db/plan__activities.50.sql#L5) file in a private repository.

**Comment by mddejong** [comment]
Just some comments from me here.

AnPlan was written for one festival per year, this was the `bfs_year` / `pac_year` field. Then when we did 2 festivals in one year I did two things: 

1. extended `bfs_year` \ `pac_year` to medium integer so we we could added the month to the festival number.
2. added `bfs_id` \ `pac_festival_id` as a new simple identifier.

You should in my opinion use the `bfs_id` \ `pac_festival_id` combo where you can. 

The `bfs_year` \ `pac_year`  is dirty and illogical by now. Up to 2020 it is just the year number, then it was year * 10 plus month: YYYYM, but that failed in 2021 when 20219 became the number for the **december** festival. Therefore I changed the size of the integer to medium so a december 2022 festival could become 202212 instead: YYYYMM. B.t.w. the `bfs_year` number is still used in many places, including the dealer order ids.

If you need something other then a number, say a unique readable string representation of the festival use the `bfs_festival_code`. This is not stored outside of `booth__festival_settings` and uniquely identifies every festival (including the old ones) as a YYYY-MM string.

**Pull request merged**
