### PR TITLE
Fix visibility filter for activity

### PR DESCRIPTION
**Pull request by janvernieuwe**

### CODE REVIEW

**Review by beverloo — APPROVED** [review]
Changing the visibility filter from a search filter to a boolean filter LGTM - the former [exists for strings](https://api-platform.com/docs/core/filters/#search-filter) which definitely isn't the right mechanism.

It's not entirely clear to me how this would fix #38 (if that's the intention), unless there are filters that are applied by default?

**Comment by janvernieuwe** [comment]
what uri are you using? the public api had pre-set filters indeed

**Comment by beverloo** [comment]
Ah, where are those defined?

I issue requests to https://animecon.nl/api/rest/activities.json

**Comment by janvernieuwe** [comment]
That uri should be fine

**Pull request merged**
